[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && cp -r dist/client/* client/ && NODE_ENV=production node dist/server/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10